apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-190236-qg56zs4vtujm-service
spec:
  selector:
    app: enterprise-system-20260520-190236-qg56zs4vtujm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
